package dev.imran.pocketbricks;

import android.app.*;import android.os.*;import android.view.*;import android.graphics.*;import android.content.*;import android.net.*;import java.util.*;

public class MainActivity extends Activity{
 static final String VERSION="1.2.0",REPO="https://github.com/imranshiundu/pocket-bricks",REL="https://github.com/imranshiundu/pocket-bricks/releases",DEV="https://imranisdev.top";
 public void onCreate(Bundle b){super.onCreate(b);requestWindowFeature(Window.FEATURE_NO_TITLE);getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);setContentView(new Game(this));}
 static class Game extends View{Paint p=new Paint(1),t=new Paint(1);Random r=new Random();Handler h=new Handler();SharedPreferences m;int W,H,score,best,last,plays,level,startLevel,lines,next,px,py;boolean run,pause,over,sound=true,set;int[][] board=new int[20][10],piece;int[][][] pcs={{{1,1,1,1}},{{1,1},{1,1}},{{0,1,0},{1,1,1}},{{1,0,0},{1,1,1}},{{0,0,1},{1,1,1}},{{0,1,1},{1,1,0}},{{1,1,0},{0,1,1}}};RectF lcd=new RectF(),grid=new RectF(),settings=new RectF();ArrayList<B> bs=new ArrayList<>();long tick;
  Runnable loop=new Runnable(){public void run(){if(run&&!pause&&!over&&SystemClock.uptimeMillis()-tick>Math.max(90,780-(level-1)*48)){tick=SystemClock.uptimeMillis();if(!mv(0,1))lock();}invalidate();h.postDelayed(this,16);}};
  Game(Context c){super(c);m=c.getSharedPreferences("pocket-bricks-memory",0);best=m.getInt("best",0);last=m.getInt("last",0);plays=m.getInt("plays",0);startLevel=m.getInt("level",1);sound=m.getBoolean("sound",true);level=startLevel;next=r.nextInt(7);h.post(loop);}float d(float v){return v*getResources().getDisplayMetrics().density;}String z(int n,int l){return String.format(Locale.US,"%0"+l+"d",n);}protected void onSizeChanged(int w,int h,int ow,int oh){W=w;H=h;layout();}
  void layout(){float w=Math.min(W-d(24),d(520)),x=(W-w)/2,y=d(16),lh=Math.min(H-d(280),w*1.32f);lcd.set(x,y,x+w,y+lh);grid.set(x+d(16),y+d(86),x+w-d(145),y+lh-d(50));settings.set(lcd.right-d(55),lcd.top+d(10),lcd.right-d(10),lcd.top+d(42));bs.clear();float by=lcd.bottom+d(16),bw=(w-d(24))/3;add("START","start",x,by,bw,d(52));add("PAUSE","pause",x+bw+d(12),by,bw,d(52));add(sound?"SOUND ON":"SOUND OFF","sound",x+2*(bw+d(12)),by,bw,d(52));float cx=x+w*.34f,sz=d(72),dy=by+d(76);add("ROT","rot",cx-sz/2,dy,sz,sz);add("LEFT","left",cx-sz-d(36),dy+sz+d(12),sz,sz);add("RIGHT","right",cx+d(36),dy+sz+d(12),sz,sz);add("DOWN","down",cx-sz/2,dy+2*sz+d(24),sz,sz);add("DROP","drop",x+w-d(160),dy+sz+d(5),d(128),d(128));}void add(String l,String a,float x,float y,float w,float h){bs.add(new B(l,a,new RectF(x,y,x+w,y+h)));}
  protected void onDraw(Canvas c){p.setColor(Color.rgb(5,6,6));c.drawRect(0,0,W,H,p);p.setColor(Color.rgb(184,202,147));c.drawRoundRect(lcd,d(12),d(12),p);txt(c,"SCORE\n"+z(score,6),lcd.left+d(16),lcd.top+d(32),d(18),true);txt(c,"BEST\n"+z(best,6),lcd.left+d(190),lcd.top+d(32),d(18),true);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(d(3));p.setColor(Color.rgb(18,31,23));c.drawRect(grid,p);p.setStyle(Paint.Style.FILL);float cell=grid.width()/10;for(int y=0;y<20;y++)for(int x=0;x<10;x++)if(board[y][x]>0)cell(c,x,y,cell);if(run&&piece!=null&&!over)for(int y=0;y<piece.length;y++)for(int x=0;x<piece[y].length;x++)if(piece[y][x]>0)cell(c,px+x,py+y,cell);float sx=grid.right+d(24);txt(c,"NEXT",sx,grid.top+d(16),d(13),false);int[][] n=pcs[next];for(int y=0;y<n.length;y++)for(int x=0;x<n[y].length;x++)if(n[y][x]>0){p.setColor(Color.rgb(18,31,23));c.drawRect(sx+x*d(16),grid.top+d(38)+y*d(16),sx+x*d(16)+d(14),grid.top+d(38)+y*d(16)+d(14),p);}txt(c,"LINES\n"+z(lines,3),sx,grid.top+d(128),d(18),true);txt(c,"LEVEL\n"+z(level,2),sx,grid.top+d(202),d(18),true);txt(c,over?"GAME OVER - PRESS START":pause?"PAUSED":run?"PLAYING - KEEP STACK LOW":"READY - PRESS START",lcd.centerX(),lcd.bottom-d(20),d(13),false,Paint.Align.CENTER);drawButton(c,settings,"SET");for(B b:bs)drawButton(c,b.r,b.a.equals("sound")?(sound?"SOUND ON":"SOUND OFF"):b.l);if(set)drawSet(c);}void cell(Canvas c,int x,int y,float s){if(y<0)return;p.setColor(Color.rgb(18,31,23));c.drawRect(grid.left+x*s+d(1),grid.top+y*s+d(1),grid.left+(x+1)*s-d(1),grid.top+(y+1)*s-d(1),p);}void drawButton(Canvas c,RectF r,String l){p.setColor(Color.rgb(35,36,36));c.drawRoundRect(r,d(18),d(18),p);txt(c,l,r.centerX(),r.centerY()+d(5),d(13),true,Paint.Align.CENTER);}void drawSet(Canvas c){p.setColor(Color.argb(245,5,6,6));RectF o=new RectF(lcd.left+d(12),lcd.top+d(50),lcd.right-d(12),lcd.bottom-d(12));c.drawRoundRect(o,d(12),d(12),p);txt(c,"SETTINGS",o.left+d(18),o.top+d(36),d(18),true);txt(c,"Start level: "+z(startLevel,2)+"   tap LEFT/RIGHT to change",o.left+d(18),o.top+d(80),d(13),false);txt(c,"Memory: best "+z(best,6)+"  last "+z(last,6)+"  plays "+z(plays,3),o.left+d(18),o.top+d(112),d(13),false);txt(c,"Install real app: open GitHub Releases and download Pocket-Bricks.apk",o.left+d(18),o.top+d(150),d(12),false);txt(c,"Updates: APK checks releases manually; no Play Store needed.",o.left+d(18),o.top+d(178),d(12),false);txt(c,"Tap DROP: APK releases | ROT: repo | DOWN: developer | PAUSE: close",o.left+d(18),o.bottom-d(28),d(11),false);}void txt(Canvas c,String s,float x,float y,float sz,boolean b){txt(c,s,x,y,sz,b,Paint.Align.LEFT);}void txt(Canvas c,String s,float x,float y,float sz,boolean b,Paint.Align a){t.setColor(Color.rgb(18,31,23));t.setTextSize(sz);t.setFakeBoldText(b);t.setTextAlign(a);for(String line:s.split("\\n")){c.drawText(line,x,y,t);y+=sz+d(6);}}
  public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_DOWN)return true;float x=e.getX(),y=e.getY();if(settings.contains(x,y)){set=!set;return true;}if(set){if(hit("left",x,y)){startLevel=Math.max(1,startLevel-1);m.edit().putInt("level",startLevel).apply();level=startLevel;}else if(hit("right",x,y)){startLevel=Math.min(15,startLevel+1);m.edit().putInt("level",startLevel).apply();level=startLevel;}else if(hit("drop",x,y))open(REL);else if(hit("rot",x,y))open(REPO);else if(hit("down",x,y))open(DEV);else if(hit("pause",x,y))set=false;return true;}for(B b:bs)if(b.r.contains(x,y)){act(b.a);return true;}return true;}boolean hit(String a,float x,float y){for(B b:bs)if(b.a.equals(a)&&b.r.contains(x,y))return true;return false;}void open(String u){try{getContext().startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception e){}}
  void act(String a){if(a.equals("start")){start();return;}if(a.equals("pause")){if(run&&!over)pause=!pause;return;}if(a.equals("sound")){sound=!sound;m.edit().putBoolean("sound",sound).apply();return;}if(!run||over)start();if(pause)return;if(a.equals("left"))mv(-1,0);else if(a.equals("right"))mv(1,0);else if(a.equals("down")){if(mv(0,1))score++;else lock();}else if(a.equals("rot"))rot();else if(a.equals("drop")){while(mv(0,1))score+=2;lock();}}void start(){for(int[] row:board)Arrays.fill(row,0);score=lines=0;level=startLevel;run=true;pause=over=false;spawn();}void spawn(){piece=copy(pcs[next]);next=r.nextInt(7);px=5-piece[0].length/2;py=0;if(col(piece,px,py))end();}int[][] copy(int[][] a){int[][] o=new int[a.length][a[0].length];for(int i=0;i<a.length;i++)System.arraycopy(a[i],0,o[i],0,a[i].length);return o;}boolean mv(int dx,int dy){if(!col(piece,px+dx,py+dy)){px+=dx;py+=dy;return true;}return false;}boolean col(int[][] q,int ox,int oy){for(int y=0;y<q.length;y++)for(int x=0;x<q[y].length;x++)if(q[y][x]>0){int bx=ox+x,by=oy+y;if(bx<0||bx>=10||by>=20)return true;if(by>=0&&board[by][bx]>0)return true;}return false;}void rot(){int[][] q=new int[piece[0].length][piece.length];for(int y=0;y<piece.length;y++)for(int x=0;x<piece[y].length;x++)q[x][piece.length-1-y]=piece[y][x];if(!col(q,px,py))piece=q;}void lock(){for(int y=0;y<piece.length;y++)for(int x=0;x<piece[y].length;x++)if(piece[y][x]>0&&py+y>=0)board[py+y][px+x]=1;clear();spawn();}void clear(){for(int y=19;y>=0;y--){boolean f=true;for(int x=0;x<10;x++)if(board[y][x]==0)f=false;if(f){lines++;score+=100*level;level=startLevel+lines/10;for(int yy=y;yy>0;yy--)board[yy]=board[yy-1].clone();board[0]=new int[10];y++;}}best=Math.max(best,score);save();}void end(){run=false;over=true;last=score;plays++;best=Math.max(best,score);save();}void save(){m.edit().putInt("best",best).putInt("last",last).putInt("plays",plays).apply();}}
 static class B{String l,a;RectF r;B(String l,String a,RectF r){this.l=l;this.a=a;this.r=r;}}
}
